# LookaRetro — ROM importer (Windows)
#
# Scans %RETRO_HOME%\roms\<system>\ for ROM files and (re)generates each
# system's metadata.pegasus.txt with DIRECT emulator launch commands, so the
# games show up in Pegasus Frontend. Run it every time you add/remove ROMs:
#
#     powershell -ExecutionPolicy Bypass -File "%USERPROFILE%\Retro\scripts\import-roms.ps1"
#
# It reads %RETRO_HOME%\scripts\emulators.ps1 (written by install-windows.ps1)
# for the resolved emulator locations, and falls back to common paths.

$ErrorActionPreference = 'Stop'

$RETRO_HOME = if ($env:RETRO_HOME) { $env:RETRO_HOME } else { Join-Path $env:USERPROFILE 'Retro' }
$ROMS_DIR    = Join-Path $RETRO_HOME 'roms'
$EMU_FILE    = Join-Path $RETRO_HOME 'scripts\emulators.ps1'

if (Test-Path $EMU_FILE) { . $EMU_FILE }

function Resolve-First {
    param([string[]]$Candidates)
    foreach ($c in $Candidates) {
        if ($c -and (Test-Path $c)) { return $c }
    }
    return $null
}

if (-not $RetroArch   -or -not (Test-Path $RetroArch))   { $RetroArch   = Resolve-First @($env:RETROARCH, (Join-Path $RETRO_HOME 'emulators\RetroArch\retroarch.exe'), 'C:\RetroArch-Win64\retroarch.exe') }
if (-not $DuckStation -or -not (Test-Path $DuckStation)) { $DuckStation = Resolve-First @($env:DUCKSTATION, (Join-Path $RETRO_HOME 'emulators\DuckStation\duckstation-qt-x64-ReleaseLTCG.exe')) }
if (-not $Dolphin     -or -not (Test-Path $Dolphin))     { $Dolphin     = Resolve-First @($env:DOLPHIN, (Join-Path $RETRO_HOME 'emulators\Dolphin\Dolphin.exe'), (Join-Path $env:LOCALAPPDATA 'Dolphin Emulator\Dolphin.exe')) }
if (-not $CoresDir    -or -not (Test-Path $CoresDir))    { $CoresDir    = Resolve-First @($env:CORES_DIR, (Join-Path $env:APPDATA 'RetroArch\cores'), (Join-Path $RETRO_HOME 'emulators\RetroArch\cores')) }

function Clean-Title {
    param([string]$Name)
    $t = $Name
    $t = $t -replace '\.[^.]*$', ''          # first extension
    $t = $t -replace '\.[^.]*$', ''          # second (.nkit.iso)
    $t = $t -replace '\s*\((USA|Europe|Japan|Brazil|World|Japan, USA|USA, Europe|En,Fr,De|En,Ja|Rev [0-9A-Za-z]|v[0-9.]+)\)', ''
    $t = $t -replace '\s*\[(USA|Europe|Japan|Brazil|World)\]', ''
    $t = $t -replace '[_-]+', ' '
    $t = $t -replace '\s+', ' '
    return $t.Trim()
}

$systems = @(
    @{ key='snes'; title='Super Nintendo (SNES)'; exts=@('sfc','smc','fig','swc','bs') },
    @{ key='gbc';  title='Game Boy Color';        exts=@('gbc','gb') },
    @{ key='gba';  title='Game Boy Advance';      exts=@('gba','agb') },
    @{ key='n64';  title='Nintendo 64';           exts=@('z64','n64','v64','ndd') },
    @{ key='nds';  title='Nintendo DS';           exts=@('nds','dsi') },
    @{ key='psx';  title='PlayStation 1';         exts=@('cue','chd','pbp','m3u','iso') },
    @{ key='wii';  title='Nintendo Wii';          exts=@('wbfs','rvz','iso','ciso') }
)

$cores = @{ snes='snes9x_libretro'; gbc='gambatte_libretro'; gba='mgba_libretro'; n64='mupen64plus_next_libretro'; nds='melonds_libretro' }

foreach ($sys in $systems) {
    $dir  = Join-Path $ROMS_DIR $sys.key
    $meta = Join-Path $dir 'metadata.pegasus.txt'
    New-Item -ItemType Directory -Force -Path $dir | Out-Null

    $files = foreach ($e in $sys.exts) { Get-ChildItem -Path $dir -Filter "*.$e" -File -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName }

    if ($sys.key -eq 'psx') {
        # Prefer disc descriptors (.cue/.chd/.pbp/.m3u/.iso); fall back to raw .bin
        if (-not $files) { $files = Get-ChildItem -Path $dir -Filter '*.bin' -File -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName }
    }

    $files = @($files | Where-Object { $_ } | Sort-Object -Unique)

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by LookaRetro import-roms.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
    $lines.Add("# Re-run to refresh.")
    $lines.Add("")
    $lines.Add("collection: $($sys.title)")
    $lines.Add("shortname: $($sys.key)")

    if ($sys.key -eq 'psx') {
        if ($DuckStation) {
            $lines.Add('launch: "' + $DuckStation + '" -fastboot -fullscreen -- "{file.path}"')
        } else {
            $lines.Add('# launch: (DuckStation not found — run install-windows.ps1)')
        }
    }
    elseif ($sys.key -eq 'wii') {
        if ($Dolphin) {
            $lines.Add('launch: "' + $Dolphin + '" -e "{file.path}"')
        } else {
            $lines.Add('# launch: (Dolphin not found — run install-windows.ps1)')
        }
    }
    else {
        $core = $cores[$sys.key]
        if ($RetroArch -and $CoresDir) {
            $lines.Add('launch: "' + $RetroArch + '" -L "' + (Join-Path $CoresDir ($core + '.dll')) + '" "{file.path}"')
        } else {
            $lines.Add('# launch: (RetroArch not found — run install-windows.ps1)')
        }
    }

    $lines.Add("")

    if ($files.Count -gt 0) {
        foreach ($f in $files) {
            $name = [System.IO.Path]::GetFileName($f)
            $lines.Add("game: $(Clean-Title $name)")
            $lines.Add("file: $name")
            $lines.Add("")
        }
    } else {
        $lines.Add("# No ROMs found yet. Drop your files in this folder, then re-run:")
        $lines.Add("#   powershell -ExecutionPolicy Bypass -File `"$RETRO_HOME\scripts\import-roms.ps1`"")
        $lines.Add("")
    }

    [System.IO.File]::WriteAllLines($meta, $lines, (New-Object System.Text.UTF8Encoding -ArgumentList $false))
    Write-Host "OK $($sys.key): $($files.Count) game(s) -> $meta"
}

Write-Host ""
Write-Host "Done. Restart Pegasus Frontend (or press F5 in the theme) to reload."
