#!/usr/bin/env bash
# LookaRetro — ROM importer.
#
# Scans $RETRO_HOME/roms/<system>/ for ROM files and (re)generates that
# system's metadata.pegasus.txt so the games show up in Pegasus Frontend.
# Run it every time you add or remove ROMs:
#
#     ~/Retro/scripts/import-roms.sh
#
# NOTE: compatible with the stock macOS bash 3.2 (no bash-4 features).
set -euo pipefail

RETRO_HOME="${RETRO_HOME:-$HOME/Retro}"
ROMS_DIR="$RETRO_HOME/roms"
SCRIPTS_DIR="$RETRO_HOME/scripts"
LAUNCHER="$SCRIPTS_DIR/launch.sh"

# Clean a file name into a display title.
clean_title() {
    local name="$1"
    # strip extension(s) and multi-disc markers
    name="${name%.*}"            # .iso / .wbfs / ...
    name="${name%.*}"            # .nkit
    # handle contraction underscores
    name="$(printf '%s' "$name" | sed -E "s/_s\b/'s/g; s/_re\b/'re/g; s/_t\b/'t/g")"
    # strip dump/bracket tags: [!], [b], etc.
    name="$(printf '%s' "$name" | sed -E 's/\[[^]]*\]//g')"
    # strip common region tags
    name="$(printf '%s' "$name" | sed -E 's/\((USA|Europe|Japan|Brazil|World|En,Fr,De|En,Ja|En,Fr|Rev [0-9A-Za-z]+|v[0-9.]+|U|E|J|UE|JU|M[0-9]+|Xenophobia|frieNDS|SweeTnDs|EP[0-9.]+|GamesMaster Special Edition|Japan, USA|USA, Europe)\)//gi')"
    name="$(printf '%s' "$name" | sed -E 's/\(!\)//g')"
    # trim trailing/leading whitespace before checking suffix
    name="$(printf '%s' "$name" | sed -E 's/[[:space:]]+$//; s/^[[:space:]]+//')"
    # handle trailing ", The" -> "The ..."
    if [[ "$name" =~ (,[[:space:]_]*[Tt]he)$ ]]; then
        name="$(printf '%s' "$name" | sed -E 's/,[[:space:]_]*[Tt]he$//')"
        name="The $name"
    fi
    # separators to spaces
    name="$(printf '%s' "$name" | sed -E 's/[_-]+/ /g')"
    # collapse spaces
    name="$(printf '%s' "$name" | sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//')"
    printf '%s' "$name"
}

for system in snes gbc gba n64 nds psx wii 3ds switch psvita; do
    case "$system" in
        snes)   title="Super Nintendo (SNES)"; exts="sfc smc fig swc bs" ;;
        gbc)    title="Game Boy Color";        exts="gbc gb" ;;
        gba)    title="Game Boy Advance";      exts="gba agb" ;;
        n64)    title="Nintendo 64";           exts="z64 n64 v64 ndd" ;;
        nds)    title="Nintendo DS";           exts="nds dsi" ;;
        psx)    title="PlayStation 1";         exts="cue chd pbp m3u iso" ;;
        wii)    title="Nintendo Wii";          exts="wbfs rvz iso ciso" ;;
        3ds)    title="Nintendo 3DS";          exts="3ds cci cxi app" ;;
        switch) title="Nintendo Switch";       exts="nsp xci nsz" ;;
        psvita) title="PlayStation Vita";      exts="vita vpk zip" ;;
    esac

    dir="$ROMS_DIR/$system"
    meta="$dir/metadata.pegasus.txt"
    mkdir -p "$dir"
    [[ -d "$dir" ]] || continue

    # Collect entry-point files into a temp list (one path per line).
    tmpf="$(mktemp)"
    : > "$tmpf"

    collect() {
        local e f
        for e in $1; do
            for f in "$dir"/*.$e; do
                if [[ -f "$f" ]]; then
                    printf '%s\n' "$f" >> "$tmpf"
                fi
            done
        done
        return 0
    }

    if [[ "$system" == "psx" ]]; then
        # Prefer .cue/.chd/.pbp/.m3u/.iso (multi-track discs have one .cue);
        # fall back to raw .bin only when no disc descriptor exists.
        collect "$exts"
        if [[ ! -s "$tmpf" ]]; then
            collect "bin"
        fi
    else
        collect "$exts"
    fi

    sort -u "$tmpf" -o "$tmpf"
    count=0
    if [[ -s "$tmpf" ]]; then
        count=$(wc -l < "$tmpf" | tr -d ' ')
    fi

    tmp_meta="$(mktemp)"
    {
        printf '# Generated by LookaRetro import-roms.sh — %s\n' "$(date '+%Y-%m-%d %H:%M')"
        printf '# Re-run to refresh.\n\n'
        printf 'collection: %s\n' "$title"
        printf 'shortname: %s\n' "$system"
        printf 'launch: "%s" %s "{file.path}"\n\n' "$LAUNCHER" "$system"

        if [[ "$count" -gt 0 ]]; then
            while IFS= read -r f; do
                [[ -n "$f" ]] || continue
                base="$(basename "$f")"
                existing_block=""
                if [[ -f "$meta" ]]; then
                    existing_block="$(awk -v f="$base" 'BEGIN { RS=""; FS="\n" } { for(i=1;i<=NF;i++) if ($i ~ "^file:[[:space:]]*" f "$") { print $0; found=1; exit } } END { if (!found) exit 1 }' "$meta" 2>/dev/null || true)"
                fi
                if [[ -n "$existing_block" ]]; then
                    printf '%s\n\n' "$existing_block"
                else
                    t="$(clean_title "$base")"
                    printf 'game: %s\n' "$t"
                    printf 'file: %s\n\n' "$base"
                fi
            done < "$tmpf"
        else
            printf '# No ROMs found yet. Drop your files in this folder, then re-run:\n'
            printf '#   %s/import-roms.sh\n\n' "$SCRIPTS_DIR"
        fi
    } > "$tmp_meta"
    mv "$tmp_meta" "$meta"

    rm -f "$tmpf"
    echo "✓ $system: ${count} game(s) -> $meta"
done

echo
echo "Done. Restart Pegasus Frontend (or press F5 in the theme) to reload."
