#!/usr/bin/env bash
# LookaRetro — generate the "LookaRetro Config" collection for Pegasus.
#
# Creates:
#   $RETRO_HOME/roms-settings/metadata.pegasus.txt
#
# Every entry is a settings action (console mode, sleep, N64 renderer, ...)
# that Pegasus launches directly — no terminal needed. Re-run after changing
# the actions (or run "Atualizar listas" from inside Pegasus). bash 3.2 OK.
set -euo pipefail

RETRO_HOME="${RETRO_HOME:-$HOME/Retro}"
SETTINGS="$RETRO_HOME/scripts/pegasus-settings.sh"
OUT_DIR="$RETRO_HOME/roms-settings"

mkdir -p "$OUT_DIR"
META="$OUT_DIR/metadata.pegasus.txt"

{
    printf '# Generated by LookaRetro make-settings-catalog.sh — %s\n' "$(date '+%Y-%m-%d %H:%M')"
    printf '# Settings toggles for the console. Re-run after updating the actions.\n\n'
    printf 'collection: LookaRetro Config\n'
    printf 'shortname: lookaretro\n'
    printf 'description: Ajustes do LookaRetro — modo console/sleep, N64, controles e listas.\n\n'
} > "$META"

entry() {  # $1 = nome  $2 = ação  $3 = stub  $4 = descrição
    # stub file so Pegasus always lists the entry (same pattern as the
    # open-source catalog); the per-game launch line runs the action.
    [[ -e "$OUT_DIR/$3" ]] || : > "$OUT_DIR/$3"
    {
        printf 'game: %s\n' "$1"
        printf 'file: %s\n' "$3"
        printf 'launch: "%s" %s\n' "$SETTINGS" "$2"
        printf 'developer: LookaDev\n'
        printf 'genre: Configuração\n'
        printf '\n%s\n\n' "$4"
    } >> "$META"
}

entry "Modo Console — nunca dormir" "console" "console.flag" \
    "Ativa o modo console: o Mac nunca dorme (nem com a tampa fechada). Pede a senha de administrador."
entry "Modo Normal — dormir" "sleep" "sleep.flag" \
    "Restaura o sleep normal do macOS (10 min + tampa fechada). Pede a senha de administrador."
entry "N64 — Turbo (GPU)" "n64-turbo" "n64-turbo.flag" \
    "Renderizador ParaLLEl-RDP via Vulkan: N64 rápido com aceleração de GPU."
entry "N64 — Compatível" "n64-compat" "n64-compat.flag" \
    "Renderizador Angrylion (software): mais compatível, porém mais lento. Use se um jogo abrir preto no Turbo."
entry "Reconfigurar Controles" "controls" "controls.flag" \
    "Reaplica o mapeamento dos 2 controles (P1/P2, Dolphin GC/Wii, DuckStation rumble)."
entry "Atualizar Listas de Jogos" "refresh" "refresh.flag" \
    "Reverifica as pastas de ROMs e regenera as listas. Depois pressione F5 no Pegasus."

echo "✓ LookaRetro Config: 6 ação(ões) -> $META"
echo "  (abra no Pegasus e pressione F5 para ver a coleção)"
