# LookaRetro — generate the "Open Source" collection for Pegasus (Windows).
#
# Reads %RETRO_HOME%\catalog\open-source.tsv and creates:
#   %RETRO_HOME%\roms-open-source\metadata.pegasus.txt
#   %RETRO_HOME%\roms-open-source\<filename>   (0-byte stub until first play)
#
# Each game's `launch:` calls fetch-and-play.ps1, which downloads the ROM on
# first play. Re-run after editing the catalog.

$ErrorActionPreference = 'Stop'

$RETRO_HOME = if ($env:RETRO_HOME) { $env:RETRO_HOME } else { Join-Path $env:USERPROFILE 'Retro' }
$FETCHER    = Join-Path $RETRO_HOME 'scripts\fetch-and-play.ps1'
$CATALOG    = Join-Path $RETRO_HOME 'catalog\open-source.tsv'
$OUT_DIR    = Join-Path $RETRO_HOME 'roms-open-source'

if (-not (Test-Path $CATALOG)) { Write-Host "Catalog not found: $CATALOG" -ForegroundColor Red; exit 1 }

New-Item -ItemType Directory -Force -Path $OUT_DIR | Out-Null

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Generated by LookaRetro make-open-source-catalog.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
$lines.Add("# These games are downloaded on first play. Re-run after editing the catalog.")
$lines.Add("")
$lines.Add("collection: Open Source")
$lines.Add("shortname: open-source")
$lines.Add("")

$count = 0
foreach ($row in Get-Content $CATALOG) {
    if (-not $row -or $row.StartsWith('#') -or $row.StartsWith('system' + "`t")) { continue }
    $f = $row -split "`t"
    if ($f.Count -lt 6) { continue }

    $system   = $f[0]
    $filename = $f[1]
    $title    = $f[2]
    $developer = $f[3]
    $license  = $f[4]
    $url      = $f[5]

    $target = Join-Path $OUT_DIR $filename
    if (-not (Test-Path -LiteralPath $target)) {
        New-Item -ItemType File -Path $target -Force | Out-Null
    }

    $lines.Add("game: $title")
    $lines.Add("file: $filename")
    $lines.Add("developer: $developer")
    $lines.Add('launch: powershell -NoProfile -ExecutionPolicy Bypass -File "' + $FETCHER + '" ' + $system + ' "{file.path}" "' + $url + '"')
    $lines.Add("genre: Homebrew (open source)")
    $lines.Add("")
    $lines.Add("License: $license. Download automático da fonte oficial na primeira execução.")
    $lines.Add("")

    $count++
}

[System.IO.File]::WriteAllLines((Join-Path $OUT_DIR 'metadata.pegasus.txt'), $lines, (New-Object System.Text.UTF8Encoding -ArgumentList $false))
Write-Host "OK Open Source: $count game(s) -> $(Join-Path $OUT_DIR 'metadata.pegasus.txt')"
Write-Host "  (first play downloads the ROM from its official source)"
