#!/usr/bin/env bash
# LookaRetro — generate the "Open Source" collection for Pegasus.
#
# Reads catalog/open-source.tsv and creates:
#   $RETRO_HOME/roms-open-source/metadata.pegasus.txt
#   $RETRO_HOME/roms-open-source/<filename>   (0-byte stub until first play)
#
# Each game's `launch:` calls fetch-and-play.sh, which downloads the ROM from
# its official URL on first play and then launches it. Re-run after editing
# the catalog. bash 3.2 compatible.
set -euo pipefail

RETRO_HOME="${RETRO_HOME:-$HOME/Retro}"
SCRIPTS_DIR="$RETRO_HOME/scripts"
FETCHER="$SCRIPTS_DIR/fetch-and-play.sh"
CATALOG="${1:-$RETRO_HOME/catalog/open-source.tsv}"
OUT_DIR="$RETRO_HOME/roms-open-source"

if [[ ! -f "$CATALOG" ]]; then
    echo "Catalog not found: $CATALOG" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"
META="$OUT_DIR/metadata.pegasus.txt"

{
    printf '# Generated by LookaRetro make-open-source-catalog.sh — %s\n' "$(date '+%Y-%m-%d %H:%M')"
    printf '# These games are downloaded on first play. Re-run after editing the catalog.\n\n'
    printf 'collection: Open Source\n'
    printf 'shortname: open-source\n\n'
} > "$META"

count=0
while IFS=$'\t' read -r system filename title developer license url; do
    # skip blank lines, comments and the header row
    [[ -n "$system" ]] || continue
    [[ "$system" == \#* ]] && continue
    [[ "$system" == "system" ]] && continue

    # create stub only if the ROM isn't already present (don't clobber downloads)
    if [[ ! -e "$OUT_DIR/$filename" ]]; then
        : > "$OUT_DIR/$filename"
    fi

    {
        printf 'game: %s\n' "$title"
        printf 'file: %s\n' "$filename"
        printf 'developer: %s\n' "$developer"
        printf 'launch: "%s" %s "{file.path}" "%s"\n' "$FETCHER" "$system" "$url"
        printf 'genre: Homebrew (open source)\n'
        printf 'summary: Licença %s. Download automático da fonte oficial na primeira execução.\n\n' "$license"
    } >> "$META"

    count=$((count + 1))
done < "$CATALOG"

echo "✓ Open Source: $count game(s) -> $META"
echo "  (first play downloads the ROM from its official source)"
